### ISSUE TITLE
Allow AJAX calls to conditionally pass through even when there is a fixture in place.

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#1043]

**Comment by justinbmeyer** [comment]
@imjoshdean this currently isn't working in the new `can-fixture` because it operates on an XHR object instead of jQuery.  That filter would be added here: https://github.com/canjs/can-fixture/blob/master/core.js#L130

Perhaps it could check `xhrSettings.data.canfixture`?

I'm going to close this as it's implemented in CanJS.  Someone can open an issue if they need it in `can-fixture`.  Maybe an alternative would be something like:

```js
fixture.off(function(){
  return $.get("foo");
})
```
