### ISSUE TITLE
Using serialize: false and route initialization causes the property to be cleared after re-serializing

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#1081]
Example A, using routes to initialize, with serialization:
http://jsfiddle.net/x8Hbd/

Example B, using routes to initialize, no serialization:
http://jsfiddle.net/r67m4/

In example B, app initializes and calls the async task setter, and the change event triggers with the loaded Task instance, however then strips the hash param, and sets the property as undefined (without calling the setter as well).

In this case, the property should either not be initialized at all, or should not be cleared when the hash param is removed.

A good solution might be to strip out any parameters that should not be serialized while calling can.route.ready, before binding to window.location.hash changes, and initializing with those properties. This way, async setters don't evoke an unintentional window.location.hash change event during serialization.

**Comment by justinbmeyer** [comment]
@Bajix I'm having trouble understanding exactly what the issue is.  

In "Example B", there's a property in the url (`task`) that is trying to set a `serialize: false` property. In general, a `serialize: false` property shouldn't have a corresponding property in the url.  

Those properties can be set normally without them being removed: http://justinbmeyer.jsbin.com/cikeli/5/edit?html,js,console

We have other serializer checkers we've added, so I'm not opposed, I just want to better understand the use case.  Thanks and sorry about the long delay.

**Comment by justinbmeyer** [comment]
@Bajix I'll reopen if you can get back to me on the details of the issue.
