### ISSUE TITLE
Binding to can.route prior to calling can.route.map, handlers aren't called

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1198]
Here's a fiddle example: http://jsfiddle.net/3a3k33w6/

I would expect this to work, when I use `can.route.bind` I expect that to always fire when the route changes, even if the underlying Map changes.

**Comment by justinbmeyer** [comment]
This would be a bit challenging to make work.  We'd have to remember all the bindings so that if the map changed, we could undo them and re-apply them to the new map.  

I don't think this is critical.  If someone else thinks it is (and wants to work on it), please re-open this issue in `can-route`.
