### ISSUE TITLE
bind with namespace doesn't work

### ISSUE THREAD

**Issue by w3dot0** [canjs/canjs#1282]
Using `can.Map.prototype.bind` with a namespaced event used to work properly (in 2.0.0) and made unbinding cleanly easier. It doesn't work anymore in 2.1.3, probably because can doesn't use jQuery's bind anymore.

Jsfiddle: http://jsfiddle.net/hk27g393/2/

jQuery documentation: http://api.jquery.com/bind/#entry-longdesc

>If the eventType string contains a period (.) character, then the event is namespaced. The period character separates the event from its namespace. For example, in the call .bind( "click.name", handler ), the string click is the event type, and the string name is the namespace. Namespacing allows us to unbind or trigger some events of a type without affecting others. See the discussion of .unbind() for more information.

Are namespaced events still supposed to work?

**Comment by justinbmeyer** [comment]
Namespaced events aren't supported.  We dropped using jQuery's event system because it was so slow.  In general, you shouldn't need to bind to things directly, instead using a component's "events" object.  If this is still needed in a modern CanJS application, please give an example and I'll reopen.  Thanks!
