### ISSUE TITLE
Allow stache partials to support custom context as a second parameter

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#1331]
Handlebars supports passing a context to partial as a second parameter: https://github.com/wycats/handlebars.js/blob/ce74c36118ffed1779889d97e6a2a1028ae61510/spec/qunit_spec.js#L456-L462

Would be great to implement compatibility fix to Stache/Mustache templates as well.

**Comment by isadovskiy** [comment]
Any update on this?

**Comment by justinbmeyer** [comment]
nope.  But to add it to stache, you need to get makeLiveBindingPartialRenderer (https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L441) called with expressionData similar to how makeLiveBindingBranchRenderer is (https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L531).  I'm not sure why it isn't but I bet the fix is easy.  

Then, you'll need (https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L456) to be passed something like `scope.add(newContext)`.

To look up newContext, you can use 

```
var exprData = core.expressionData(expression),
```

And b/c minor's exprData is much easier to use ... you should be able to something like:

```
exprData._args[0].value(scope, options)
```

Ping me on gitter if you want to help make this happen.

**Comment by isadovskiy** [comment]
Thanks for your feedback, @justinbmeyer! If I get a chance, I'll try to implement this by myself and submit pull request.

**Comment by justinbmeyer** [comment]
Closing for issue in can-stache
