### ISSUE TITLE
validations::errors isn't an observable

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#1584]
The errors method in validations isn't an observable and therefore can't be used in computed properties.

It would be ideal to create define getters that depend on certain errors, but errors is just a function that runs validations and returns an object with the errors observed.

The whole validations plugin seems out of date and maybe should be rethought or deprecated as suggested in https://github.com/bitovi/canjs/issues/1111

It would be nice to do things like:

````html
<span class='errors'>{{errors.email}}</span>
````

**Comment by daffl** [comment]
I thought @alexisabril worked on making validation errors observable at one point?

**Comment by rjgotten** [comment]
@daffl
https://github.com/bitovi/canjs/blob/398f2dfcfcd401f637f957b37ff3b4b5cf63b9ab/map/validations/validations.js#L155

Note the `self.attr( attr )` bit there? That's what makes a call to `errors` observable, provided errors itself is wrapped inside a `can.compute`. The old EJS view engine wraps assignment-type code nuggets into one automatically, which is why it works there if you use expressions such as `<%= obj.errors() %>` in your views.

I presume the stache engine is different?

**Comment by daffl** [comment]
No, it should work just the same. I'll give it a try.

**Comment by justinbmeyer** [comment]
Closing for the functionality in https://github.com/canjs/can-validate which is observable.
