### ISSUE TITLE
Standard element or <can-import> use a specified component

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1688]
For `<can-import>` it is desirable to specify another component's behavior to take over.  For example:

```
  <can-import from="app/home/home" can-tag="loading">
    <app-home></app-home>
  </can-import>
```

`can-tag="loading"` specifies another `can.view.tag` method to use for the behavior of the `<can-import>` method.  This is needed because `<can-import>s` must be statically defined.

This could also be used with standard elements like:

```
<div can-as="my-component"/>
```

Options:

 - `as="component-name"` - `as` is a suggested way of doing exactly this in webcomponents.
 - `can-as` - same as above but with can infront of it
 - `can-tag` - We are calling to can.view.tag, so this makes sense too.

**Comment by matthewp** [comment]
So what happens when you put a `can-as` on a custom tag like?

```html
<my-component can-as="other-component"></my-component>
```

I say this because `<can-import>` is implemented as a can.view.tag (for progressive loading).  If we switched to a more generic `can-as` that can be attached to any element what happens when the `can-import` callback is called, how does it know not to render its subtemplate?  Does it just check for the existence of a `can-as`?
