### ISSUE TITLE
Allow stache/system templates to import other templates and use as partials

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1689]
I would like to be able to import a partial and use it.  A few options:

## Use import / as

```
<import from="./order-items.stache!" as="orderItems"/>
{{> orderItems}}
```

I don't think `as=` should necessarily set values on the viewModel, instead, I think `as=` should be setting values on some values on options probably.

@matthewp I'm not sure how this would work with what you've done to support:

```
<can-import from="app/appstate" as="viewModel" />
```

## can-tag craziness

This is more something to think about than a real suggestion:

```
<import from="./order-items.stache!" can-tag="."/>
```

**Comment by matthewp** [comment]
We already have a solution for this (although not working with can-import at the moment):

```html
<import from="./order-items.stache!" [orderItems]="{value}" />
```

We just need to document it as part of the can-import docs.

I'm not sure what to do with the `as="viewModel"` static definitions.

**Comment by matthewp** [comment]
We might need a new syntax for this because: 

```mustache
<can-import from="./order-items.stache!" [orderItems]="{value}" />

{{> orderItems}}
```

The partial attempts to fetch orderItems.stache right away. We need to know to wait until `orderItems` is on the scope.  How about:

```
{{< orderItems}}
```

This is more unixy as well. In this case we can bind to the scope and wait for `orderItems`.

**Comment by daffl** [comment]
Couldn't we use the `can-import` Deferred (which is available right away) and wait to render until it is resolved? 

```js
<can-import from="./order-items.stache!" [orderItems]="{.}" />

{{> orderItems}}
```

**Comment by matthewp** [comment]
No, in this case the partial renderer gets called before the [] attr callback.

**Comment by matthewp** [comment]
Fixed by #1723

**Comment by gsmeets** [comment]
I've implemented an AMD loader plugin for my stache files, because I run with requirejs instead of stealjs. I've just updated the plugin to support to support the can-import tag. Partials are automatically resolved by canjs itself already when running without combining files into build layers.

For the generation of build layers I've added some code that adds imports and partials as dependencies of the stache file that requires them. For the imports I used can/view/intermediate_and_imports, for the partials I just parse the templates for the {{>}} tag. 

Can't you do the same in this case? Seems a lot of added syntax for something that doesn't do a whole lot.

(Second question: are you interested in adding the AMD loader plugin to the canjs codebase? Otherwise I'll throw up my own github repo with it.)

**Comment by matthewp** [comment]
The new syntax will exist for everything, not just stache imports.  So you can reference the viewModel of any component, such as:

```handlebars
<todo-list #todos></todo-list>

<h2>#todos.length remaining todos</h2>
```

We're just using the same syntax in this case for passing around templates, it's quite elegant IMO.

I don't think we are going to be putting plugins into this repo any more, even the Steal ones will be removed, but we could create a new repo for you under the canjs org for a RequireJS plugin, that would be quite nice actually.
