### ISSUE TITLE
Alias (name) to `each` helper context

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1735]
```mustache
{{#each readings}}
<some-component reading="{.}"/>
{{/each}}
```
Some times I want to wrap it with `<another-component>` and I have to change `{.}` to `{../.}` or even '{../../.}' for double wrap

```mustache
{{#each readings}}
<another-component/>
  <and-another-component/>
   <some-component reading="{../../.}"/>
  </and-another-component/>
</another-component/>
{{/each}}
```
If one could have name for `each` heper context and refere to it by given name, it would be more convinient without need of backtrack paths.

```mustache
{{#each readings "reading"}}
<another-component/>
  <and-another-component/>
    <some-component reading="{reading}"/>
  </and-another-component/>
</another-component/>
{{/each}}
```

emberjs does it using sintax something like like: `{{#each readings as "reading"}}`

**Comment by pYr0x** [comment]
+1, useful!

**Comment by justinbmeyer** [comment]
I'm fine with this.  You would have to make the #each helper change the scope which it sets up here:

https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_helpers.js#L34

Instead of `.add(item)`, it would be more like:

```
var context = {};
context[asValue] = item;
.add(context);
```

To make "as" work, I think we do pass the expression data, so you could see that the argument name was "as".

**Comment by justinbmeyer** [comment]
@pYr0x or @whitecolor let me know if you want to tackle it.  Thanks!

**Comment by justinbmeyer** [comment]
@dylanrtt was looking for this too.

**Comment by justinbmeyer** [comment]
Closing as: https://github.com/canjs/can-stache/issues/16
