### ISSUE TITLE
can.Component events prototype does not listen on all events in viewModel

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#1740]
Since can.Component.prototype.events is a can.Control 
https://github.com/bitovi/canjs/blob/master/component/component.js#L43
https://github.com/bitovi/canjs/blob/master/component/component.js#L377

and the lookup is set to the viewModel https://github.com/bitovi/canjs/blob/master/component/component.js#L465

i expect i can listen to all elements on the viewModel with the { } notation.

here is a JSBin that demonstrate the problem
http://jsbin.com/guxazuteba/7/edit

* for the Deferred there is no event fired at all.
* {foo} is changed by clicking, but no console log is seen
* {foobar}, which is "span", is only working

it would be also nice to listen on Deferred, for example:
```
events: {
    inserted: function(){

    },
    '{dates} resolved': function(){
      console.log('dates is resolved');
    }
  }
```

**Comment by daffl** [comment]
It depends on what we are listening to:

1. Deferreds are observable in templates but not on the control. You'd have to `.then()` them manually.
2. The best way to listen to specific property changes is `'{scope} foo': function(el, ev) {}`.

**Comment by dylanrtt** [comment]
I think the curly braces in templated event handlers should always surround an object so the ```{foo} change``` syntax doesn't really make sense since ```foo``` is not an object so how can you listen to a change event on it? You would think you could use this:

```js
' foo': function(){
  console.log('foo changed');
},
```

but that will only listen to the control's element due to hardcoding at [#L225](https://github.com/bitovi/canjs/blob/master/control/control.js#L226) because ```ready.delegate``` will be undefined because can.sub did not return an array in [_action](https://github.com/bitovi/canjs/blob/master/control/control.js#L141) since there were no curly braces in the string. Perhaps ```' foo'``` should actually listen to the view-model.

Personally, I think the convenience of allowing the view-model to be the first point of lookup is unnecessary and only serves to confuse people. The standard syntax which @daffl pointed out is clear and *should* be the only way of listening to the scope in my opinion.

**Comment by pYr0x** [comment]
@dylanrtt: {foo} is an compute and computes are observable. 
daffls way (syntax) to listen at a compute is not clear. since we can listen at changes in can.List http://canjs.com/docs/can.List.html#section_Listeningtochanges and can.Control http://canjs.com/docs/can.Control.html#section_Listeningtoevents, i think we should have the same syntax for listen at the viewModel.
i thought about:
```
'{viewModel.foo} change': function(){}
```

**Comment by dylanrtt** [comment]
Ah, I overlooked that `foo` is a compute.

In that case, it seems reasonable to expect your latest example to work, but it seems to only work on Maps and Lists, not computes. :(

I suppose it could be considered a bug but when would this actually be necessary? Your example seems a bit unlikely because you placed a compute instance on the prototype whereas using define seems to be the more appropriate choice. Using define, the ```foo``` property takes on a slightly different form so I think the typical ```{viewModel} foo``` does make sense (and works).

Also, I just realized the _action method is basically rewritten in the component control so most of what I said in my previous comment doesn't apply.

**Comment by pYr0x** [comment]
so hello again ;)

i would like to pick up this issue again.

i have made a example where a component is listen to events on the viewModel.

http://jsbin.com/lakefonulo/edit?js,console,output

in this example you can see how to write event-listener for different properties in the viewModel.
* can.List
* normal key - value property

the event-listener work fine.
can we add this example in the component API description for viewModel? This would be nice.
http://canjs.com/docs/can.Component.prototype.viewModel.html

**Comment by daffl** [comment]
This is showing all the correct events right? I agree, it would make a good example, so if you would like to add it, http://canjs.com/docs/can.Component.prototype.events.html (by editing https://github.com/bitovi/canjs/blob/master/component/events.md) is probably the best spot. Can you submit a PR?

**Comment by justinbmeyer** [comment]
Just an FYI:

- Computes on the prototype are deprecated.  So `'foo': can.compute(0),` shouldn't be done.
- In general, using events on an "events" object should be avoided.  The define plugin on the viewModel can almost always be used instead.

**Comment by pYr0x** [comment]
@justinbmeyer I can't listen to add items to a can.List in the define plugin. The set-function would not trigger if I push a item. You can try this on my example above..

**Comment by justinbmeyer** [comment]
@pYr0x yeah, figuring out how define would work with can.List is one of the big remaining holes in the CanJS army.

**Comment by pYr0x** [comment]
@justinbmeyer i am wondering, you have created this weapon ;) so you know best how to handle this :)
as you said: "using events on an "events" object should be avoided". do you have a alternative for listening for change or add events on a can.List

**Comment by justinbmeyer** [comment]
@pYr0x Why are you listening to events on the list?

**Comment by pYr0x** [comment]
@justinbmeyer for sideeffects...

i pushed multiple objects into a list in a component.
``{id: 0815, name: 'foo'}``
on each push i want to take ID value and pushed this ID into an other list (named: ids) in the component. 
the ids-list is an can.List with all IDs. this list i need for an ajax request.

actual i do somthink like this:
``
saveTour: function(el, ev){
            ev.preventDefault();

            var wwanlagen = [];
            this.stations.each(function(el, index){
               wwanlagen.push(el.attr('wwanlage_id'));
            });

            var tour = new Tour({wwanlagen: wwanlagen});
            tour.save(function(response){
                if(response.attr('result') === 'ok') {
                    global.tt.setLocation(Config.baseUrl + '/uebersicht');
                }
            });
        },
``

``wwanlagen`` is the IDs-List

**Comment by justinbmeyer** [comment]
@pYr0x I'm confused why you have to listen to `this.stations`.  Why do you need to keep that derived list always available and not simply generate it when `saveTour` is called?

So, this is what `can-derive` is attempting to solve cc @akagomez .

The performance of can-derive isn't better than just re-creating a list until you probably have about 500 items.  

To re-create the list, you could currently do:

```js
define: {
  wwanlagen: {
    get: function(){
      return this.attr("stations").map(function(station){ return station.attr("wwanlage_id") })
    }
  }
}
```

or if you want to make sure the list instance itself isn't changing:

```js
define: {
  wwanlagen: {
    Value: can.List
    get: function(lastSet){
      return lastSet.replace( this.attr("stations").map(function(station){ return station.attr("wwanlage_id") }) )
    }
  }
}
```

it might seem inefficient to create a brand new list everytime, but it's pretty fast until you get to 500 or so items.

**Comment by justinbmeyer** [comment]
I'm going to close this.  I don't think promises need to be bindable in `events` because they are non-leaky.  Someone can always listen to when the property changes and `.then` the promise like this shows:


http://justinbmeyer.jsbin.com/petufa/edit?js,console,output
