### ISSUE TITLE
Custom can.Model.List.Map has no effect

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#1745]
Defining a custom can.Model.List is supported. But can.List.Map described at http://canjs.com/docs/can.List.Map.html does have any effect and the returing Map in findAll() is no instance of can.Model or of a custom Map

i have found this line
https://github.com/bitovi/canjs/blob/master/model/model.js#L517
but i am not sure if this is the right way
i tried:
```
this.constructor.List.Map.setup.apply(this, arguments);
```
but no luck

**Comment by rjgotten** [comment]
Have a look at https://github.com/bitovi/canjs/blob/master/model/model.js#L397-L404
Those are what is handling the carry-over of the `Map` member onto the model list if you are passing a custom list type as part of the static properties.

I should add that those lines are totally unncessary and a really, really wrong workaround for a bug that originates back in the static `can.Map.setup` that is called by the static `can.Model.setup` as part of the class construction/declaration. 

The base `can.Map.setup` sets up a `can.List` subtype with a 'strongly typed' `Map` member: https://github.com/bitovi/canjs/blob/master/map/map.js#L80-L85

However, it does so by directly extending `Map.List` a.k.a. `can.Map.List` a.k.a. `can.List`. `can.Model` has it's own dedicated `can.Model.List` and attempts to patch another list over the top, but fails in doing it 100% correctly.

That entire piece of patch code can be kicked out by altering the static `can.Map.setup` to extend `this.List` instead of `Map.List`. The class setup will then naturally extend `can.Map.List` for subclasses of `can.Map` and naturally extend `can.Model.List` for subclasses of `can.Model`...

**Comment by pYr0x** [comment]
thanks @rjgotten for the explanation. but it seems that the whole extending part is a little bit too difficult for me.
you said, you patched this in your own fork. can you create a pull request?

**Comment by rjgotten** [comment]
> you said, you patched this in your own fork. can you create a pull request?

I patched this in an old 2.0.x build that underwent customization to use a *sane* relative module ID lookups when loaded via AMD / RequireJS. The technical stuf behind it is probably not really of interest to you, but let's just say that the default way CanJS is shipped for AMD is hostile to proper integration with other code and goes against best practices.

It's impossible to create a pull request against current versions based on that modified production export without resorting to headache inducing cherry-picking.

I'd sooner set-up a fresh re-patch in the current HEAD revision and that's saying something, because the last time I tried to author a pull request based on the HEAD revision, I ran into issues even getting my fork set up correctly with working sub-dependency repositories and had issues with the used toolchain that required installing additional dependencies completely outside of the normal Windows OS workflow.

Until that crap gets cleaned out and the barrier-to-entry for creating a pull request gets lowered, I'm not ever submitting one again, sorry.

Whoever on the core development team wrote this feature in the first place should be able to follow along with the notes I wrote and patch this. I assume *they* actually have their system configured for this.

**Comment by justinbmeyer** [comment]
@rjgotten The way we do it was suggested by James Burke.

**Comment by justinbmeyer** [comment]
Btw, @rjgotten if you'd like to make exporting a relative version of CanJS's AMD easy ... it would just take creating a relative version of steal-tool's AMD helper: https://github.com/stealjs/steal-tools/blob/master/lib/build/helpers/amd.js

You'd just have to copy that and paste this line:

https://github.com/stealjs/steal-tools/blob/master/lib/build/helpers/cjs.js#L113

that makes the CJS build relative in the right place.

 to export a relative version of AMD, i

**Comment by justinbmeyer** [comment]
@rjgotten if you'd like, can you email me at justin AT bitovi.com  Thanks!

**Comment by justinbmeyer** [comment]
@pYr0x Want to setup a time next week to go over this issue and #1743 ?

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-list/issues/4
