### ISSUE TITLE
can-value Not Setting Default Value of Radio Input

### ISSUE THREAD

**Issue by joe-crick** [canjs/canjs#1860]
When setting the default value of a input radio using can-value, the radio button is not checked. Please see the following JSBin:  http://jsbin.com/titoworite/1/edit?html,js,output.

**Comment by dylanrtt** [comment]
Hmm, maybe this could be better documented but `can-value` with radio buttons is designed to work with strings like in this example:

http://jsbin.com/vekofocoqo/edit?html,js,console,output

```html
<input type="radio" can-value="{foo}" value="apple"> apple
<input type="radio" can-value="{foo}" value="banana"> banana
<input type="radio" can-value="{foo}" value="cucumber"> cucumber
```

If the radio element's `value` matches the `foo`'s value, then it's checked. This means you basically need to use strings because the browser doesn't understand much else in the way of form controls.

If you need to do the common use case of yes/no radio buttons instead of a checkbox for a boolean property, you could try my solution for this with custom attributes.

http://jsbin.com/zozuhevosa/2/edit?html,js,output

**Comment by justinbmeyer** [comment]
This should be fixed with https://github.com/canjs/can-stache/issues/17 like:

```
  True <input type="radio" name="foo" {($checked)}="foo" />
  
  False <input type="radio" name="foo" {($checked)}="not(foo)" />
```

```
can.stache.registerConverter("not",{
  get: function(source){
    return !source();   
  },
  set: function(newVal, source){
    source(!newVal); 
  }
});
```
