### ISSUE TITLE
Syntax that prevents setting parent scope on binding initialization.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2050]
Sometimes, you want to prevent setting the parent scope on initialization.  

For example, with DOM related bindings: https://github.com/canjs/canjs/issues/1834#issuecomment-129639753

And with Component bindings: https://github.com/canjs/canjs/issues/2020

Currently, the parent scope is only set if it is undefined, and the child has a value.  I think we should add another modifier that prevents setting the parent.

Some options:

- `({$value})="key"` 
- `})$value({="key"`
- `({$value="key"`

**Comment by dylanrtt** [comment]
I have kind of come around on this topic. In general, while it still feels wrong to me, updating the parent scope during initialization probably can't be very harmful. I initially discovered it was happening because a late loaded binding was changing a property (from undefined to empty string) to which another component was listening. I easily got around it by just setting a default empty string.

I hesitate to add another syntax as if we don't already have enough. If I am the only one complaining about how the new bindings work, you can probably put this on the back burner.

As for the syntax options, I don't really have an opinion and I will probably not even use this feature.
