### ISSUE TITLE
can.map.validations taken "error" variable in template

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2071]
Using can.map.validations causes an error.
it uses the variable "errors" and so i can't use this variable anymore in my template

also accessing the error method in map.validations is not possible

here a demo
http://jsbin.com/vivutoxiya/edit?html,js,console,output

**Comment by Macrofig** [comment]
You want to use [can-validate](https://github.com/canjs/can-validate) now. It has the ability work with any validation library (with a provided shim), and the errors object is now an observable. 

That said, it also uses the `errors` property on the map instance. I created an issue to make can-validate's can.Map plugin work with any property you desire.

Although, the errors object is a can.Map which means you can manipulate it if you wish. I'm trying to make a JSbin to demonstrate this.

**Comment by Macrofig** [comment]
Ok, check this out: http://jsbin.com/difibeq/edit?html,js,console,output

So you can manipulate the errors object when you instantiate your map but you have to remember that the validation library expects a certain structure. In this case, I'm using [validate.js](http://validatejs.org/). ValidateJS returns a map of arrays when validating multiple properties.

Quick explanation why: Each item in the map is mapped to a property. Because each property can have multiple validation rules, there can be multiple errors. These errors are represented by the array.

So, you can push your own data into the errors object if you need to, just make sure you stick with the structure of your chosen library.

One last note, can-validate will clear the errors object if it finds that the validation rules it is aware of have all passed.

This brings me to a question, *why do you need to manually edit the errors object?*

**Comment by justinbmeyer** [comment]
@pYr0x I'm going to put a deprecation notice on can/map/validations and point people at `can-validate`.  I'm also going to mark this as `wont-fix` because it's not something we are going to prioritize (but I will accept a pull request).  

@Macrofig where are the generated docs for this plugin?

**Comment by justinbmeyer** [comment]
Re-openning until the deprecation docs are in place.

**Comment by Macrofig** [comment]
Docs were up at some point here: canjs.github.io/can-validate/
I was trying to fix the demos and it looks like I broke the whole thing. I'll fix it today. https://github.com/canjs/can-validate/issues/8
