### ISSUE TITLE
In a Control, not all events caught with Control.on are rebound when Control.on() is called

### ISSUE THREAD

**Issue by fantanamihai** [canjs/canjs#2084]
In CanJS, events can be caught in 4 ways:
Mode 1. In a Control, using Control.on

> ```
>   can.Control.extend('EventWithOn', {}, {
>     init: function() {
>       this.on(this.element, 'eventWithOn', 'eventWithOnHandler');
>    },
> 
>    eventWithOnHandler: function() { ... }
> ```

Mode 2. In a Control, if events have a special character in their name, by declaring a method with the same name

> ```
> can.Control.extend('EventWithSpecialCharacter',{}, {
> 
>    'eventWith.SpecialCharacter': function() { //can automatically binds method with an event having the same name 
>      ...
>   }
> })
> 
> can.trigger(window, 'eventWith.SpecialCharacter') //trigger the event
> ```

Mode 3. Using can.$.event.special

> ```
>    $.event.special['eventDeclaredWithSpecial'] = function() {... }
> ```

Mode 4. Declaring a Control processor for the event 

> See http://canjs.com/docs/can.Control.processors.html

However, issues occur when events are rebound using Control.on() as following:
- Declaring events handlers using Modes 2, 3 and 4 - work as expected
- Usign Mode 1, the _eventWithOn_ is rebound as expected **if and only if** the event has a special character **and** the _eventWithOnHandler_ has the same name as the event (see https://github.com/canjs/canjs/blob/master/control/control.js#L102)

In documentation (http://canjs.com/docs/can.Control.prototype.on.html), it should be clarified how events work in a Control, and perhaps that events caught are best to have a special character in their name **and** method handlers should have the same name as the event.

**Comment by justinbmeyer** [comment]
@meconcomputer When you say:

> Usign Mode 1, the eventWithOn is rebound as expected if and only if the event has a special character and the eventWithOnHandler has the same name as the event (see https://github.com/canjs/canjs/blob/master/control/control.js#L102)

I'm confused.  Why would someone use __both__ `this.on` and an `action` to  listen to the same event.  In the following example, why would someone have the `this.on` when `foo.bar` is already going to listen to what they want:

```
  can.Control.extend('EventWithOn', {}, {
    init: function() {
      this.on(this.element, 'foo.bar', 'foo.bar');
   },
   'foo.bar': function(){

   }
```

**Comment by justinbmeyer** [comment]
The reason why I wrote the previous comment is that `.on` doesn't rebind any events .. ever.  The only reason it seems like a rebinding is happening is because the "Mode 2" binding:

```
'foo.bar': function(){  }
```

is listening to the same thing and being rebound.

So the rules are simple:

 - Actions are rebound
 - bindings with `this.on` are not rebound.

What is an action is anything that:

 - has a special character
 - in $.event.special
 - or is a DOM event like "click", "keypress", etc

Btw, are you making heavy use of Controls?  You might switch to components which are able to avoid a lot of the manual event binding that was associated with can.Control.

**Comment by meconcomputer** [comment]
Thank you Justin for your comments (and label) that underlines best what this issue is about.

> Why would someone use both this.on and an action to listen to the same event.
That is a confusion rising from documentation, because there is no clear statement to differentiate between ``this.on bindings`` and ``actions``.

Just to conclude, please include in the documentation your statements, accompanied by example. It will be clear for everyone what are some of the foundations Can has (especially for beginners):

### Bindings:
+ Actions are rebound
+ bindings with this.on are not rebound.

### An action is anything that:
+ has a special character
+ in $.event.special
+ a DOM event like "click", "keypress", etc

**Comment by pYr0x** [comment]
@meconcomputer would you be nice to add a documentation part?

**Comment by meconcomputer** [comment]
Yeah sure, I'll try to do that. Thanks for the invite

**Comment by justinbmeyer** [comment]
Closing as can-component in 3.0 is able to rebind w/o calling `.on()`
