### ISSUE TITLE
Passing a function reference with @ runs it

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2116]
http://jsbin.com/veyisiwesi/edit?html,js,console

```html
<foo-bar {child}="@parent"></foo-bar>
```

The `parent` function shouldn't run until called. Worked in 2.3.2. If I use a 2-way binding, it runs twice (but I would never do that with a proto function).

**Comment by justinbmeyer** [comment]
I might do a quick fix so that `<foo-bar {@child}="@parent"></foo-bar>` works.

**Comment by dylanrtt** [comment]
No rush for me. I'll just stay in 2.3.2 for now. I saw you fixed some of my other issues but there's just too many right now.

**Comment by justinbmeyer** [comment]
This one was caused by unifying all binding logic.  Essentially, a compute is made for `child`.  When the compute is set to a `function`, computes automatically re-read themselves to get their new value.  

In this case "child" is read, which ends up calling the function.  Instead if `@child` was read, things will work.  This is also needed for two-way binding.

**Comment by dylanrtt** [comment]
Are you suggesting that `<foo-bar {@child}="@parent"></foo-bar>` should be the correct syntax for 1-way binding a function parent-to-child?

**Comment by justinbmeyer** [comment]
Yes, it's the necessary syntax.  Unless we want to special case things.

**Comment by dylanrtt** [comment]
Fine by me. Whatever makes things easier.

**Comment by dylanrtt** [comment]
Are you still planning to do #2065 eventually or just leave it with double @ as the norm?

**Comment by justinbmeyer** [comment]
@dylanrtt the reason is that `{^method}="parent"` would call `method` and set `parent` to its return value, while `{^@method}="@parent"` would export the function itself to `@parent`.

Regarding #2065, yes, I might be able to special case `@` so it's not needed on both sides in 1-way bindings.  Basically, I can prevent the "setter" compute from having to ever read itself.  

But I want to think about it a bit first.

**Comment by dylanrtt** [comment]
The `@` modifier makes sense when reading values, not writing them. Adding `@` to the destination has no meaning. With `{^@method}="@parent"`, you are not assigning to `@parent`, but to `parent`.

**Comment by justinbmeyer** [comment]
Could it have meaning?  Say we had data like:

```
var compute = can.compute();
var map = new Map({compute: compute});
```

Would there be a difference between `@compute` and `compute` when setting?

**Comment by dylanrtt** [comment]
Interesting. I suppose that would depend on what the current behavior is, which I originally thought (I could be wrong) is that it always assigns directly to the property. That is, the hypothetical `@` destination syntax would keep the current behavior.

If I'm right so far, omitting `@` would allow you to instead call a function/compute on the destination with the assigned value, but that behavior can already be achieved by defining the component that way, so having the syntax flexibility would allow the component to be used multiple ways.

Then you may have to consider a scenario where the developer wants different read/write functionality when using `@` on both sides.

**Comment by pYr0x** [comment]
@justinbmeyer we should be documented this behaivor better... 
the only parts i found is:
http://canjs.com/docs/can.stache.key.html
and
http://canjs.com/docs/can.view.bindings.toParent.html#section_ExportingFunctions

**Comment by justinbmeyer** [comment]
@pYr0x what needs to be documented better?  There's an example showing how to export a parent function.

**Comment by justinbmeyer** [comment]
@pYr0x well, we should probably add a similar example for the other direction: http://canjs.com/docs/can.view.bindings.toChild.html

@dylanrtt I've made it possible to drop the `@` on the receiving side of a one way binding.  So `{child}="@method"` and `{^@method}="parent"` will work.  I think a lot of people will try this.  And it should work.  It's likely that even if there could be a difference between:

- `{child}="@method"`
- `{@child}="@method"`

That difference would only matter if in fact `child` pointed to a compute and we could detect that and do the right thing, while still allowing `{child}="@method"` for the vast majority of use cases.

I think the docs should continue to show `@` on both sides.  I think it's good guidance because they are needed for two way bindings.

**Comment by pYr0x** [comment]
@justinbmeyer on the documentation http://canjs.com/docs/can.view.bindings.toParent.html#section_ExportingFunctions

<my-panel {add-panel}="@*addPanel" title="CanJS">CanJS Content</my-panel>

Shouldn't the @ not be on both sides?

**Comment by justinbmeyer** [comment]
@pYr0x it works both ways.

**Comment by pYr0x** [comment]
@justinbmeyer but you said
> I think the docs should continue to show @ on both sides. I think it's good guidance because they are needed for two way bindings.
