### ISSUE TITLE
two-way binding bug regarding select dropdowns when value is set in inserted or init

### ISSUE THREAD

**Issue by halcyonandon** [canjs/canjs#2134]
http://jsfiddle.net/sjxsazoh/3/

{^$value}="countryCode" - Works
{($value)}="countryCode" - Doesn't work
can-value="{countryCode}" - No longer works

**Comment by pYr0x** [comment]
dont know which behavior you expect?
in the first dropdown 
```<select class="country-list" {^$value}="countryCode" name="countryCode" id="countryCode">```
you export the element value to countryCode with a one-way-binding.

if you change this to:
```<select class="country-list" {(^$value)}="countryCode" name="countryCode" id="countryCode">```
all three dropdowns change simultaneously

**Comment by dylanrtt** [comment]
@pYr0x The issue being demonstrated is that changes to viewModel properties during `events.init()` or `events.inserted()` do not update `<select>` elements using the new 2.3 binding rules. The 2nd and 3rd select menus should show "INDIA" initially, not "USA".

Here's a slightly simplified example:
http://jsbin.com/fizuniyoju/edit?html,js,output

The bug affects `can-value` as well because it shares code with the new bindings.

It doesn't seem to be a problem with other form controls. There are a few open issues about select element live binding already; they sure could use some love.
