### ISSUE TITLE
{{.}} does not create a compute

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#2238]
When using `{{.}}`, we should be able to set(in addition to getting) the context value. For instance, a primitive array's element value cannot currently be set using `{($value)}`.

Example below:

http://jsbin.com/nezewi/2/edit?html,js,output

**Comment by justinbmeyer** [comment]
@alexisabril did we fix this?

The solution is to make the context observable on a Scope and to make it possible to set the context on a scope.

**Comment by alexisabril** [comment]
@justinbmeyer There's a commit on this issue already, however tests weren't running on Travis at the time of that issue. https://github.com/canjs/canjs/commit/b1015ae20f4bdc7ff586e99787207717d225a4ff

**Comment by prashantsharmain** [comment]
@justinbmeyer can we pair up on this? I'm getting 8 test failures in stache_test.js when I incorporate the fix for #2309. Following is one such failed test case. (I'll continue to investigate in the meantime)

can/view/stache dom: Helpers can be passed . or this for the active context (2, 0, 2) Rerun
Expected:	"Justin is attending Reception"
Result:	"Justin is attending "
Diff:	 "Justin  is  attending Reception" " 
Source:	
    at Object.<anonymous> (http://localhost:8000/view/stache/stache_test.js:2346:4)
    at Object.Test.run (http://localhost:8000/node_modules/steal-qunit/qunit.js:1303:18)
    at http://localhost:8000/node_modules/steal-qunit/qunit.js:1463:10
    at process (http://localhost:8000/node_modules/steal-qunit/qunit.js:1016:24)
    at http://localhost:8000/node_modules/steal-qunit/qunit.js:186:5

**Comment by justinbmeyer** [comment]
@prashantsharmain yep.  How does your Friday look?  It will be the only day I have available.

**Comment by justinbmeyer** [comment]
solved in 3.0
