### ISSUE TITLE
Cannot use CanJS with WebPack

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2374]
Tried to load up CanJS using webpack:
```
Uncaught ReferenceError: steal is not defined
```

So I tried loading can@furiosa with webpack, and got a ton of parseing errors:
```
WARNING in ./~/can/view/view.js
Critical dependencies:
113:6-13 require function is used in a way in which dependencies cannot be statically extracted
114:9-16 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/can/view/view.js 113:6-13 114:9-16

WARNING in ./~/can/view/autorender/autorender.md
Module parse failed: /Users/adamlbarrett/Spikes/react-spike/node_modules/can/view/autorender/autorender.md Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/adamlbarrett/Spikes/react-spike/node_modules/webpack/node_modules/acorn/dist/acorn.js:918:13)
    at Parser.pp.getTokenFromCode (/Users/adamlbarrett/Spikes/react-spike/node_modules/webpack/node_modules/acorn/dist/acorn.js:2810:8)
    at Parser.pp.readToken (/Users/adamlbarrett/Spikes/react-spike/node_modules/webpack/node_modules/acorn/dist/acorn.js:2505:15)
    at Parser.pp.nextToken (/Users/adamlbarrett/Spikes/react-spike/node_modules/webpack/node_modules/acorn/dist/acorn.js:2497:71)
...etc...
```

Is there a way to use CanJS with webpack?

**Comment by justinbmeyer** [comment]
Probably configuring webpack to load the AMD distribution.

**Comment by cherifGsoul** [comment]
Does the AMD distribution available as npm package?

**Comment by justinbmeyer** [comment]
Yes. It's in dist/amd

**Comment by cherifGsoul** [comment]
Yeah, I missed that

**Comment by justinbmeyer** [comment]
So is this closed? It should be possible.

**Comment by BigAB** [comment]
It might be important, with the continuing popularity of webpack, to have it seamless work for webpack users alongside their other npm modules, without needing to add "additional configuration" just for CanJS

**Comment by justinbmeyer** [comment]
@BigAB does webpack follow a special configuration like Browserify's `browser` config that we specify here:

https://github.com/canjs/canjs/blob/master/package.json#L201

**Comment by justinbmeyer** [comment]
I assume it will work by default with 3.0 if webpack supports typical CommonJS setups.

@daffl we might need to change our imports to not use `moduleName/` and instead write everything out explicit so it works in NodeJS / other setups.

**Comment by matthewp** [comment]
To really "support" WebPack (or any other loader / bundler) you have to test against it. I don't think we should support WebPack or any other loader / bundler in that respect. The only thing we should officially support is:

* Node.js
* Steal (we get this for free because canjs uses Steal in development)
* Global (for fiddles)

By my count there's at least 6 somewhat popular loader / bundler options (WebPack, Browserify, Rollup, RequireJS, JSPM, Steal) and that number will like increase when/if script type=module and the Loader spec ships.

I think all loader integration should be handled by the community. If there are Rollup fans, they can run the canjs tests against rollup in their own project and provide patches for bugs.  We can even go as far as to make it part of the release process for community projects that are active enough to test in a timely fashion.

Luckily converting to plain commonjs means that most loaders / bundlers will just work, but there's always the possibility of loader-specific bugs.  We did the "support everything" already with DOM libraries and I don't think we benefited much.  There's a huge maintenance burden to trying to support everything. And it affects how soon you can deprecate things; we are *still* supporting a dead project (YUI) because semver says we have to.

**Comment by BigAB** [comment]
Still, removing steal specific stuff like `moduleName/` is probably still a good idea

**Comment by ccummings** [comment]
I got it working after reading about some approaches someone else tried on [SO](http://stackoverflow.com/questions/34951224/using-canjs-with-webpack)

I went with approach 3 which goes like this:

1. In webpack configuration add the following to the `resolve` property:

  ```
  alias: {
    'can$': 'can/dist/cjs/can.js',
    'can': 'can/dist/cjs'
  }
  ```
2. Change `@loader` to `raw!` [here](https://github.com/bitovi/canjs.com/blob/master/cjs/view/stache/add_bundles.js#L10) and install the `raw-loader` dependency.
3. Comment out [this conditional](https://github.com/bitovi/canjs.com/blob/master/cjs/map/define/define.js#L14)

**Comment by whitecolor** [comment]
> To really "support" WebPack (or any other loader / bundler) you have to test against it. I don't think we should support WebPack or any other loader / bundler in that respect. The only things we should officially support is:

makes me sad :crying_cat_face:

**Comment by matthewp** [comment]
@whitecolor can you explain your concern?  To be clear, canjs 3.0 will load directly in Node. So if WebPack is able to bundle a normal npm package (which it definitely can) then there is no problem here.  Adding testing for every bundler essentially just tests that the bundler has basic bundling capabilities..

**Comment by whitecolor** [comment]
I think that dealing/testing library with different loading scenarios will just make it better eventually. There are some problems add issues may be specific for webpack or browserify, but people use this loader, many people, and this should be solved - it is in the interests of canjs.

In particular I had some troubles loading can with webpack, I solved them (by actually modifying can source with webpack loader to remove some unsupported stuff like `return` statement in CJS outside the function and some other - it was just quick fix for me), but user should not have such problems with popular scenarios.

**Comment by matthewp** [comment]
If we were continuing on using the `steal()` syntax in 3.0 I would agree, but since we are converting to plain commonjs and testing against Node, I think the maintenance burden (which would be large) is not worth the cost.  If we run into a lot of people having issues maybe we should reconsider.

By the way, the `return` statement issue is a webpack bug, it's completely allowed to do this in commonjs (and works fine in Node, browserify, and Steal).  We did change it not to do this in 3.0 though.

**Comment by whitecolor** [comment]
I only state that you should not ignore popular loader and do some check with them.

**Comment by lewismoten** [comment]
The real problem is JavaScript itself has never allowed you to use `return` outside of a function. This is a bug in Node that they haven't fixed (https://github.com/nodejs/node-v0.x-archive/issues/6254). So although CanJS is targeting only Node/Steal/Global, it seems to be missing the problem - CanJS is not JavaScript compliant in some areas and taking advantage of a bug!

The ECMAScript 1st edition (ECMA-262) specification states:

> An ECMAScript program is considered syntactically incorrect and may not be executed at all if it contains a return statement that is not within the Block of a FunctionDeclaration.

(page 55) http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf

This is why our programs are explicitly having problems with the CanJS files.

Some programs I have seen that don't like this:

1. ESLint will just give you a parsing error: 'return' outside of function
2. Acorn (used by Webpack / babel) - Module parse failed: ...node_modules\can\dist\cjs\map\define\define.js 'return' outside of function (248:4) You may need an appropriate loader to handle this file type.
3. UglifyJS - has a flag (--bare-returns) to allow this code for anyone supporting Node. It is setup to throw an error by default.
4. Visual Studio will have JS1018 - https://msdn.microsoft.com/en-us/library/e7c1ycsk(v=vs.90).aspx

Is there an ETA when or if this will be addressed?

**Comment by matthewp** [comment]
3.0, which is in prerelease now.

**Comment by justinbmeyer** [comment]
closing as 3.0 will take care of this.
