### ISSUE TITLE
PUT,DELETE problem on can.Model

### ISSUE THREAD

**Issue by arti1793** [canjs/canjs#2427]
Found a problem in PUT and DELETE of can.Model. When passing arguments in **update** method, the arguments are spoiling.
![err](https://cloud.githubusercontent.com/assets/7501396/16444507/fa4cb07e-3de6-11e6-874b-70c3163c7a66.PNG)
when it should be:
![success](https://cloud.githubusercontent.com/assets/7501396/16444526/12588350-3de7-11e6-8549-1f7307818ca4.PNG)
**Delete** method is not working at all.
We fixed this by commenting strings in models.js into this:

```
		ajaxMaker = function (ajaxMethod, str) {
			return function (data) {
				// data = ajaxMethod.data ?
					// ajaxMethod.data.apply(this, arguments) :
					// data;
				return ajax(str || this[ajaxMethod.url || "_url"], data, ajaxMethod.type || "get");
			};
		},
and this
makeRequest = function (modelObj, type, success, error, method) {
...
	if (type === 'update' || type === 'destroy') {
				// args.unshift(getId(modelObj));
			}
...
```

How to solve this problem?

**Comment by pYr0x** [comment]
please more info how your code look like. how do you call the update method and what does it contain?

**Comment by arti1793** [comment]
`Basket = can.Model.extend({update:'PUT http://144.76.10.46:8889/api/v1/basket'})`
`Basket.update({"products_with_options_list":[{"products_with_options_id":9809,"quantity":5}]},successCallback})`
 It wraps arguments in 'id' or in some cases in 'undefined' like on a screenshot.

save() is making put to url from location.pathname, that's why i didn't use it.

**Comment by justinbmeyer** [comment]
@arti1793 This is because you aren't calling `save` and haven't specified the `id` property.  Your objects must have an `id` for update to be called correctly.  

Demonstrated here:

http://jsbin.com/kididu/edit?html,output

![js_bin_-_collaborative_javascript_debugging_and_untitled_ __users_justin_dev_can-define](https://cloud.githubusercontent.com/assets/78602/18217368/fcf10aaa-7121-11e6-9086-2f1814d520b8.png)
