### ISSUE TITLE
CanJS Homepage Finalization

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2497]
- [x] - Make sure intro content is right.
  - Should we direct people to the guide page in general? _If you are new to CanJS, start with the Guides page that walks you through getting acquainted with the project._
- [ ] - Make a new tortoise / hair image
  - Launch should be to the right.  
  - Fix the rabbit's foot.
  - Take up less vertical space.
  - Make it work w/ mobile.
- [x] Organize Collections
  - Make sure everything is linked and has the right version.
  - Sort alphabetically or by importance.
  - Make sure descriptions are understandable.
- [x] - Remove `Support / Contributing`

**Comment by pYr0x** [comment]
I just found a view bugs on the new homepage. http://canjs.github.io/canjs/doc/can-stache-converters.html
I use a iPad version 9.3.5
1. The "on this page" is not working.
2. The multiple select demo is not working. @matthewp 
3. Scrolling is strange, because you don't see a scroll bar and you can swipe for scrolling on the iPad. Scrolling stucks always.
