### ISSUE TITLE
Improve Map value() functions ~13

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2529]
Default `value()` functions within can-map-define should have better rules that allow reading from other `value()` functions and initial values provided to the map constructor (e.g., `new can.Map({a: 5})`). The current behavior doesn't work as I would expect.

In the following example, the default `value()` function for `a` is evaluated first. It tries to read `this.attr('b')`, but `b` doesn't have a value yet, so it returns `undefined`. In this scenario, I think it would be reasonable for the `value()` function of `b` to be read during the `this.attr('b')` call to resolve it, similar to how computes work.

``` js
var Map = can.Map.extend({
  define: {
    a: {
      value: function() {
        return this.attr('b');
      }
    },
    b: {
      value: function() {
        return 5;
      }
    }
  }
});

var map = new Map();

console.log(map.attr()); // { b: 5 }
```

http://jsbin.com/liquwuroge/edit?js,console

I thought that instantiating the map instance with an initial value for `b` might resolve the problem, but when I do that, the `value()` functions never seem to be able to read any of the initial values (same effect as above).

Also, if I instantiate a 2nd map from the same constructor with an initial value for `b` like this:

``` js
var map = new Map({b: 10});

console.log(map.attr()); // { a: 5, b: 10 }
```

The `value()` function of `a` seems to have received a cached default value for the `b` (5) rather than using the provided initial value (10).

Unfortunately, the lack of versatility with `value()` leads me to use `get()` more often, which can be a problem because computes introduce performance overhead.

**Comment by justinbmeyer** [comment]
This is fixed with `DefineMap`: http://justinbmeyer.jsbin.com/conupel/1/edit?html,js,console which initializes `value`s dynamically (it's much smarter ... `value` isn't called until the first time the property is read).

Back porting this to `Map` might be tricky.  I thought @akagomez gave it a try, but it appears to not work in all cases.  Although as a work around, you can define your properties in the order they should be instantiated: http://justinbmeyer.jsbin.com/ticevo/1/edit?js,console


I'm going to close this and label it "needs a hero".  I'll help / pair with anyone who wants to fix it.  But I'm not going to pursue it at this time.

**Comment by justinbmeyer** [comment]
re-openned.   I'm going to label it P4.  It's still a bug ... we should fix it if we get time.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-map-define #33](https://github.com/canjs/can-map-define/issues/33) via [**ZenHub**](https://www.zenhub.com/)
