### ISSUE TITLE
CanJS Flow Super Issue

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2547]
This is a super issue for improving new user uptake with the new CanJS site.

The goal is to move someone effectively from the `introduction` phase to the `experiment` phase.  Specifically, this means getting people to start the `Chat Guide`.

This means getting people to navigate between the following pages (with associated issues):
- [x] Homepage #2497
- [x] Guides page #2546
- [x] Mission and Goals page  #2495
- [x] Technical Highlights page #2496
- [x] Chat Guide #2493

It will be nice to have some analytics setup tracking how people navigate this flow to make sure we're doing it right.  It might be worth some user testing too.

**Comment by chasenlehara** [comment]
I don’t think the above flow is effective for new users. Here is some feedback I received during the usability sessions:

- The [Guides page](http://canjs.com/doc/guides.html) is entirely too lengthy and not focused on what should be the next step: a getting started guide.
- The [Mission page](http://canjs.com/doc/guides/mission.html) seems more geared towards our clients, not other developers.
- There isn’t a compelling reason to care about the project’s mission until the technology is explained; similarly, the sales pitch is unexpected when the tech hasn’t been explained.
- The [Technical Highlights](http://canjs.com/doc/guides/technical.html) page doesn’t “highlight” the tech; it’s way too much information early on.

Overall, the site isn’t conducive to new users because it prioritizes things that aren’t important to them until they’ve learned more about the framework.

I think we can make this better by prioritizing these things, starting from the home page:
- A quick summary of what CanJS is (a frontend JS framework)
- A brief overview of its best features/concepts (components, model, observables, etc.)
- A getting started guide

Here are the steps we can take to do that:
- [Remove the collections from the home page](https://github.com/canjs/canjs/issues/2868)
- [Provide a higher-level overview of all the core APIs](https://github.com/canjs/canjs/issues/2865)
- De-emphasize things like the mission and [contribution guides](https://github.com/canjs/canjs/issues/2864)

I am still working through my thoughts on this, so please understand that the above are my first ideas that still need to be refined. Input is welcome!
