### ISSUE TITLE
Small docs issue

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2622]
![2016-10-25_2331](https://cloud.githubusercontent.com/assets/22180/19713388/588a9756-9b0b-11e6-976b-8b623ef3cdd2.png)

**Comment by garrettreed** [comment]
@justinbmeyer I may need your help understanding escaping in bit-docs. I figure the fix should be made in `bit-docs-generate-html/stmd.js`, but any change I make there breaks everything...

The use of `<` in signature blocks also comes across escaped, but not `>`. So that is somewhat related.

![screen shot 2016-10-28 at 5 38 51 pm](https://cloud.githubusercontent.com/assets/4079858/19823198/5d833318-9d35-11e6-9f13-531e119f8561.png)

**Comment by justinbmeyer** [comment]
I think can-import is probably written out already escaped so things are escaped twice. We just need to change can-imports docs.

**Comment by garrettreed** [comment]
Still stumped. Changing out the `&lt;can-import&gt;` for `<can-import>` in `steal-stache` docs doesn't make a difference here. There is a line in the `makeLinks` helper of `bit-docs-generate-html` that escapes the link text. I figured that was the root of the second escape, but removing that didn't make a difference either.

**Comment by garrettreed** [comment]
The steal-stache change will need to be published before this issue can be closed.
