### ISSUE TITLE
Homepage design

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2752]
Add design elements and content above the fold on the homepage.

Specifically, there are 3 types of content we might add, but we'll likely just pick two of them:
 * helloworld code sample in a jsbin
 * tiled buttons/images for chat guide links (Chat guide, TodoMVC guide, ATM guide)
 * images of apps using canjs and their company name

A designer should play with some options for including these, and then we'll decide what works best

**Comment by tomgreever** [comment]
Here's one suggestion including the tiled buttons for the guides. 

Do we really want screenshots of the app? Or would company logos suffice? 

![screen shot 2016-11-16 at 11 06 02 am](https://cloud.githubusercontent.com/assets/326843/20357267/de71d3ce-abec-11e6-91c6-a8e2d7edca7d.png)

**Comment by tomgreever** [comment]
@justinbmeyer or @brianmoschel can I get the hello world jsbin code example to include in this?

**Comment by moschel** [comment]
I like the tiled guides links, looks like something I want to click. Tom, please use use any other jsbin for the purpose of this design exercise, we'll replace it if we move forward with the option

**Comment by marshallswain** [comment]
> Do we really want screenshots of the app? Or would company logos suffice?

Company logos won't (likely) expire like apps do.

**Comment by tomgreever** [comment]
Ok, I added a screenshot of a JSBin and moved things around. I'm uncertain if this is the look we're going for here, so any feedback from @justinbmeyer is welcome. I've not included company logos yet. Trying to avoid over designing it, so as a result everything is just kinda on the page. I'm not sure what to do next.
http://share.bitovi.com/TJOOEZ/#g=1&p=v3_home

![screen shot 2016-11-16 at 4 20 31 pm](https://cloud.githubusercontent.com/assets/326843/20368227/bf85db96-ac18-11e6-879b-f477cbf7f0e2.png)

**Comment by andreaalmeida** [comment]
Updated homepage design:
- Re-organized side navigation pages (mockup included)
- Added border around turtle hare images so that they look more like one image, instead of two separate ones
- Moved NPM Package, Github Star, and GitHub edit links/buttons in-line with page title
- Styled Edit page in Github link to look like a button
- Removed collections and packages sections (now live on API docs page)
- Added logos of companies that use CanJS
- Increased font-weight of "on this page" to make it more noticeable 


![artboard 3new](https://cloud.githubusercontent.com/assets/5323173/25757184/c967da26-3186-11e7-9da4-3274c09a62d1.jpg)

![canjs_sitemap](https://cloud.githubusercontent.com/assets/5323173/25757411/8cfc2276-3187-11e7-81b1-c9166017b0ad.jpg)

**Comment by andreaalmeida** [comment]
Mockup of API Docs page - moved Collections and package sections from homepage
![apidocs](https://cloud.githubusercontent.com/assets/5323173/25757862/7f5d30d6-3189-11e7-9194-e2efbd1b7341.jpg)
