### ISSUE TITLE
Move the “Collections” and “The can Package” sections off the home page

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2868]
The “Collections” list is confusing (is “collections” a CanJS term?) and daunting (there are so many APIs!). Those sections might be more useful on a main “API” page, where someone could more easily find all of the CanJS APIs.

**Comment by justinbmeyer** [comment]
Where would we move the API page?  Why would moving it make it less daunting?

**Comment by chasenlehara** [comment]
I have a different issue open for either [moving or removing the current API Guide](https://github.com/canjs/canjs/issues/2863) page.

This issue is related to the [Collections section on the home page](http://canjs.com/#Collections). It can be overwhelming for new users to see so many APIs listed on the home page because it makes CanJS look monolithic and complicated. The framework isn’t as approachable with so many modules, especially because of all the jargon.

I think it would be appropriate to list all of the modules on a main API page, which would make it easier to find what you’re looking for when you’re familiar with the terms.

**Comment by justinbmeyer** [comment]
the idea behind all the libraries was to make it less monolithic :-(

**Comment by chasenlehara** [comment]
Which it is! Conceptually, it’s not so monolithic either: there are a few basic concepts (components, observables, etc.) that are easy for new users to grasp. I think emphasizing those basic concepts first will make it easier for new users to get started.

**Comment by frank-dspeed** [comment]
The Real Importent things are Mixed Tutorials thats all whats realy missing to make it easyer for new people i think i trained the last days over 50 people to code Can3 and i got the most fast success via showing them how to port existing projects and code to CanJS Code because near any Javascript Coder starts with Jquery for example so its for him Realy easy once you told him look this is a jQuery app and then tell him how he can shorten that code with CanJS
