### ISSUE TITLE
Add debugging guides

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3416]
Opening this issue (maybe it’ll be an epic?) for us to add guides on how to debug CanJS applications. We might create one epic guide (under [Guides](https://canjs.com/doc/guides.html)), although I think it would make sense for each module to have its own debugging guide (similar to how `can-set` has this [Solving Common Issues](https://canjs.com/doc/can-set.html#SolvingCommonIssues) section).

**Comment by chasenlehara** [comment]
Related: https://github.com/canjs/can-connect/issues/347 https://github.com/canjs/can-stache/issues/282

**Comment by frank-dspeed** [comment]
@chasenlehara i am for adding npm module debug to all can libs like define on all places and then we can debug all stuff well i did that for can define direktspeed/can-define-debug@f390eb0

it helped me a lot https://www.npmjs.com/package/debug

i use it also backend side for all projects i did forks of every can package but don't published them and can this way debug them all

a commun method that i use then is i add to the init of my app that if env DEBUG exists in the node start line then i add directly in the init the settings to the localstorage in browser

because you need to filter out very verbose things like babel :) they all are using that module and if you do something like DEBUG=* you get with steal and babel a lot of fun :)

so DEBUG=,-babe is most importent if you debug whole projects if you debug only a single component turn on debug for babel is also cool

**Comment by chasenlehara** [comment]
https://canjs.com/doc/guides/debugging.html
