### ISSUE TITLE
Investigate how we can avoid cyclic can-* dependencies

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3497]
We run into issues when we add a new `can-*` dependency in order to test something and that dependency depends on the current package.

For instance, adding `can-stache` to test something in `can-view-scope` when `can-stache` already depends on `can-view-scope`.

```
can-view-scope
└── can-stache
    └── can-view-scope
```

We should avoid this. It would be awesome if we had a lint rule or some kind of postinstall hook that would check for this and let people know not to do it.

**Comment by frank-dspeed** [comment]
only way i could figure out is:
-npm hook pre install script in package.json
that links to a js file that get called and finds out if deps already exist in upper folders.
and then look if version is statisfied if not it would be a good idea to cycle because the version depends then not really on the other because of the version.
```
scripts: {
 preinstall: "node ./not_cycle_dependencys"
}
```

**Comment by justinbmeyer** [comment]
I'd use a lint rule. We don't need to have hooks that consumers would hit.

**Comment by bmomberger-bitovi** [comment]
I've been evaluating different cyclic dependency options to run in canjs to catch things during build.

The fastest one seems to be with `nocycle`: https://www.npmjs.com/package/nocycle .  Use this node script during the build to check for a cycle in our scripts in `can.all` (we can also make our own printer that would warn appropriately):

```javascript
require("nocycle").detect();
var GLOBAL = require("can-global");
var global = GLOBAL();
require("can-simple-dom");
require("can-vdom");
global.document = document;
global.HTMLElement = global.Node;
global.XMLHttpRequest = global.XMLHttpRequest || function() {};
global.$ = global.jQuery = require("jquery");
require("./all");
```

Another option that's completely settable from the CLI is `madge`: https://www.npmjs.com/package/madge .  This is slower than nocycle but could be done with just a bash script instead of setting up a custom server-side can instance:

```bash
find node_modules/can-* -name "*.js" | grep -Ev "node_modules.*node_modules|dist" | xargs madge --include-npm --circular
```

Most other items in my research required webpack, and were ignored as a result.  Another package, `circular-require`, didn't catch the cyclical dependency in can-zone, so I can't trust it to find anything else.

**Comment by phillipskevin** [comment]
Nice job researching this @bmomberger-bitovi. I added https://github.com/canjs/canjs/issues/3544 to implement it.
