### ISSUE TITLE
Create script that will warn when adding cyclic dependencies to can-* repos

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3544]
Based on @bmomberger-bitovi's research in https://github.com/canjs/canjs/issues/3497#issuecomment-327966095, we should create a script that uses [nocycle](https://www.npmjs.com/package/nocycle) to detect circular dependencies and add that as part of our `npm test` script to detect things like:  

```
can-view-scope
└── can-stache
    └── can-view-scope
```

- [x] create script
- [x] create codemod or DoneJS plugin that will add the script and update the `npm test` script
- [x] run it on can-* repos

**Comment by justinbmeyer** [comment]
done script to add it

**Comment by bmomberger-bitovi** [comment]
I spent today making a custom dependency checker which is fast and robust (i.e. it doesn't fail due to duplicate can-types et al. like the nocycle version tended to).  The package is at https://github.com/canjs/detect-cyclic-packages (also on npm), and the codemod to install this package and modify package.json to include the CLI call in the test script is now packaged at https://github.com/canjs/detect-cycles-codemod (also on npm)

**Comment by bmomberger-bitovi** [comment]
I've set my script up to also look at the devDependencies at the top level because it hindered our ability to easily upgrade during the can-reflect era.  With this stipulation in place, we currently have a cyclic dependency problem with can-connect and can-fixture.  Let's talk about this on Monday.

**Comment by bmomberger-bitovi** [comment]
Also can-observation still dev-references computes and the map types.

**Comment by bmomberger-bitovi** [comment]
can-util -> can-vdom (dev-dep)

**Comment by bmomberger-bitovi** [comment]
Other than can-connect, this has been implemented across the board.  Closing.
