### ISSUE TITLE
can.data not available in can@3.13 build

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4041]
The can.all build doesn’t have can.data available on it, causing the 3.x playlist editor js bin to not work when you drag videos: https://jsbin.com/meqowis/3/edit?html,css,js,output

**Comment by phillipskevin** [comment]
Previously, `can-util/can-util` was getting pulled in by `can-construct-super`: 
![image](https://user-images.githubusercontent.com/5851984/37318142-d4ee1748-2636-11e8-9c2d-faa011f578bf.png)

I specifically fixed this in [can-construct-super@v3.1.4](https://github.com/canjs/can-construct-super/releases/tag/v3.1.4) to be compatible with 4.0.

I think we should add an import for `can-util/can-util` in the 3.0 `can/can.js`.

In 4.0, I think we should change `can-util` so each of the modules we want people to use add themselves to `can-namespace` instead of having one big catch-all.




So I don't forget how I figured this out later, I ran a build:
```
./node_modules/.bin/steal-tools build --main can/all
```

and then created an html page like:
```html
<!doctype html>
<script src="./dist/steal.production.js">
        window.can = require("can");
        window.steal = require("@loader");
</script>
```

**Comment by phillipskevin** [comment]
@chasenlehara do we want to close this since it is fixed in 3.13.1 or should we address 4.0 also?

**Comment by chasenlehara** [comment]
@phillipskevin We use [can.data in the playlist editor](https://github.com/canjs/canjs/blob/579144880a8c80852bf719b0c101c3c20c785dcf/docs/can-guides/commitment/recipes/playlist-editor/8-create-playlist.js#L60), so we either need to fix this in 4.0 or I can show how to use [can.domDataState](https://github.com/canjs/can-dom-data-state/blob/97f08196d01a2db90502c2764f7958a8dab0d674/can-dom-data-state.js#L98) in the guide instead.

**Comment by phillipskevin** [comment]
Yeah, I understand we need to fix it. Just wasn't sure if you wanted to use the same issue.

**Comment by chasenlehara** [comment]
I think same issue is fine.

For 4.0, I don’t think the same solution will work because some of the module versions will conflict, so I’m going to change can-util to namespace each module independently, then import what’s needed into the main `can` build.
