### ISSUE TITLE
Provide docs on running CanJS 4 in IE 11

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4098]
I think most things will work in IE 11, but some things need to be polyfilled (like WeakSet). We should document this in at least the migration guide… maybe elsewhere?

Kind of related: the only places we mention our browser support are in the [README](https://github.com/canjs/canjs#canjs) and on the [Technical Highlights](https://canjs.com/doc/guides/technical.html#BrowserandEnvironmentSupport) page. I think we should make this info more visible; it’s pretty critical for anyone choosing to use CanJS for a project.

**Comment by rjgotten** [comment]
Would be even better if there was a system in place where the dependencies that need polyfilling for IE would be actual -- you know; _dependencies_.

...as in imports
...which don't need to modify the global namespace
...so that CanJS can also be used to create bundled third-party widgets meant to run on websites outside of your direct control.

As it stands, that is no longer possible in a Post CanJS 2.x world.

**Comment by justinbmeyer** [comment]
CanJS 4.0 does minimize the cost of building CanJS applications with new features and performance improvements that are helped from things like MutationObservers and WeakMap. 

The mission is about a _balance_ of innovation and stability.  We think that it's the right time to start using these features (yay auto-mounted components and goodbye CID!), and we can still provide (what I consider) a good compatibility story (stability).  

The difference here is that we don't see polyfills as much as a burden.  CanJS has always required some polyfill for the oldest browsers it supports.  

> It also increases risk and stability. Polyfills may be incompatible or worse: become incompatible over time. (Notably when CanJS suddenly starts using an API feature that is not properly supported by a polyfill.)

As we did previously, we will test CanJS against the legacy browsers with the recommended polyfills.  CanJS can't start using a new unsupported feature because it would break its automated tests.  Are you sure this is a valid concern?

------------------------

In this [thread](https://github.com/canjs/canjs/pull/4097#issuecomment-382008004), I suggested a solution that solves the "3rd party widget" use case: 

I say we set about doing this. @rjgotten when is your timeframe for upgrading?  Can you help us with this?  Thanks!

**Comment by rjgotten** [comment]
@justinbmeyer 

My employer's currently in the planning phase for a big new family of projects, one of which will need to integrate functionality as a third-party.

I would have to consult some peover this and I can't give you an immediate answer, but the possibility of setting time aside to work on this and contribute to getting this into the framework may be there, if it means CanJS can help us get this to work smoothly. (The assumption of a polyfilled global environment is something of a thorn in the side with most of the big MV* players for us on this.)

**Comment by rjgotten** [comment]
@justinbmeyer 
Just leaving a heads-up.

The responsible development team for the upcoming client projects I mentioned in my previous comment is going to settle on using Vue.js, believing it will be a better fit for their situation.

There's no longer an immediate need from my end for the change you suggested in the other thread. We will likely not run into problems with IE 11 support and polyfills in the short term.

**Comment by chasenlehara** [comment]
I think this can be closed now. 😊 https://canjs.com/doc/guides/setup.html#IE11Support
