### ISSUE TITLE
Link from deprecated canjs docs to current best practice

### ISSUE THREAD

**Issue by mikemitchel** [canjs/canjs#4709]
It would be helpful to have a link to the new best practice of how to accomplish the same thing as the deprecated code/docs/stache helper. 

For example, https://canjs.com/doc/can-stache/keys/scope/scope.vars.html doesn't link to the `let` helper (https://canjs.com/doc/can-stache.helpers.let.html) to show the new way of passing a value directly through the template context.

Should probably also add `@deprecated` to those pages, as coming to those docs via the documentation search tool (as I did) means you can read them and not realize they are under the `deprecated` list on the left nav bar.

**Comment by cherifGsoul** [comment]
Can you help me to figure out what should be used instead of the deprecated stuff? 

[Helper Expression](https://canjs.com/doc/can-stache/expressions/helper.html) => ?
[scope.vars](https://canjs.com/doc/can-stache/keys/scope/scope.vars.html) => #let
[{{#each(expression)}}](https://canjs.com/doc/can-stache.helpers.each.html) => #for
[{{#is(expressions)}}](https://canjs.com/doc/can-stache.helpers.is.html) => ?
[{{#unless(expression)}}](https://canjs.com/doc/can-stache.helpers.unless.html) => #if?
[{{#with(expression)}}](https://canjs.com/doc/can-stache.helpers.with.html) => let
[registerPartial](https://canjs.com/doc/can-stache.registerPartial.html) => ?
[Legacy Scope Behavior](https://canjs.com/doc/can-stache.scopeAndContext.html) => ?
[{{>key}}](https://canjs.com/doc/can-stache.tags.partial.html) => ?

**Comment by rjgotten** [comment]
> [registerPartial](https://canjs.com/doc/can-stache.registerPartial.html) => ?

You shouldn't replace it by anything at all. In a proper module system, globally accessed and modified hardpoints like that are a bad, bad idea.

You should handle custom partials like you should handle custom helpers: import them at the top of consuming components and register them via the local partials collection of the component.

A more streamlined solution involves working with a build system plugged with a loader to handle `.stache`. You can add logic to such a loader to make it recognize path-style partials, e.g. `{{> ./template-relative/lookup-to/partial.stache }}` and have it automatically wire those up as local partials.

It really isn't all that hard to do. [I've done it before](https://github.com/NetMatch/webpack-stache-loader), but back then Bitovi opted to adopt a less-featureful Webpack loader as standard instead.

**Comment by cherifGsoul** [comment]
It is released on the `can-stache` package I'll close this once the website is published.

**Comment by chasenlehara** [comment]
@cherifGsoul Can this be closed now?

**Comment by cherifGsoul** [comment]
Yes, it fixed and published!
