### ISSUE TITLE
Fix the CRUD guide styles in Firefox & Safari

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5110]
Here’s how it looks in Firefox:
<img width="450" alt="Screen Shot 2019-07-08 at 10 18 44 AM" src="https://user-images.githubusercontent.com/10070176/60829499-dd6c2180-a169-11e9-8985-a02fe9a0440d.png">

Here’s what it looks like in Chrome:
<img width="448" alt="Screen Shot 2019-07-08 at 10 20 07 AM" src="https://user-images.githubusercontent.com/10070176/60829565-012f6780-a16a-11e9-8db0-23b16dbfccfd.png">

The styles should look roughly the same, or at least look good in Chrome, Edge, Firefox, & Safari.

This issue can be closed when the styles are updated in these two CodePens:

- https://codepen.io/bitovi/pen/drZgqY
- https://codepen.io/bitovi/pen/dBKzBZ

**Comment by ryangwilson** [comment]
The issue was that pseudo elements can't be applied to form elements – firefox seems to be the only strict browser on this, so needed to add a label that we can style the label to look like a checkbox and a label (with a `for=""` can control a related input.

Had to add a small amount of code to the JS:
```{{# for(todo of this.todosPromise.value) }}
<li>
   <input id="cb-{{ todo.id }}" checked:bind="todo.complete" on:change="todo.save()" type="checkbox" />
   <label class="fk-cb" for="cb-{{ todo.id }}"></label> ...
```



Still needs testing but this is that I have come up with:
![Screen Shot 2019-07-09 at 9 12 12 AM](https://user-images.githubusercontent.com/4571457/60891097-a01b9880-a22a-11e9-8e68-3fefa9a9d441.jpg)

<img width="1696" alt="Screen Shot 2019-07-09 at 9 11 54 AM" src="https://user-images.githubusercontent.com/4571457/60891113-a742a680-a22a-11e9-95d4-0794c4b6a2ba.png">


https://codepen.io/ryangwilson/pen/ewbYbd

**Comment by ryangwilson** [comment]
Made some additional changes to input/button so that it works better on smaller devices
<img width="664" alt="Screen Shot 2019-07-09 at 10 19 10 AM" src="https://user-images.githubusercontent.com/4571457/60897236-b9761200-a235-11e9-8ef3-c3d4d1792c95.png">
<img width="522" alt="Screen Shot 2019-07-09 at 10 15 36 AM" src="https://user-images.githubusercontent.com/4571457/60897238-b9761200-a235-11e9-860b-b0ab992f3cf7.png">
<img width="522" alt="Screen Shot 2019-07-09 at 10 15 05 AM" src="https://user-images.githubusercontent.com/4571457/60897239-b9761200-a235-11e9-9e37-12883da7832f.png">
<img width="498" alt="Screen Shot 2019-07-09 at 10 14 14 AM" src="https://user-images.githubusercontent.com/4571457/60897240-b9761200-a235-11e9-8fed-dc782b539218.png">
<img width="479" alt="Screen Shot 2019-07-09 at 10 13 17 AM" src="https://user-images.githubusercontent.com/4571457/60897241-b9761200-a235-11e9-952e-c60e4ca6b2dd.png">

**Comment by ryangwilson** [comment]
In testing I found that the CodePen tutorial doesn't work in Windows 10 Edge (current build)
<img width="1053" alt="Screen Shot 2019-07-09 at 10 34 59 AM" src="https://user-images.githubusercontent.com/4571457/60897316-de6a8500-a235-11e9-8c1d-e313ae17f74a.png">

Any thoughts @chasenlehara ?

**Comment by ryangwilson** [comment]
@chasenlehara save on blur or save on enter is not working for the inputs to change the todo content. I don't think it is working properly in the live CodePen either
![unfocus](https://user-images.githubusercontent.com/4571457/60904181-97ce5800-a240-11e9-9622-542aedb96d19.gif)

**Comment by ryangwilson** [comment]
CSS cleaned up and working on all major browsers (except Edge as mentioned above)
![demo](https://user-images.githubusercontent.com/4571457/60978180-c14db900-a2fe-11e9-8496-951094eebc16.jpg)
![hover-demo](https://user-images.githubusercontent.com/4571457/60978182-c14db900-a2fe-11e9-9aeb-6585deb2f1ed.jpg)
![Screen Shot 2019-07-10 at 9 34 47 AM](https://user-images.githubusercontent.com/4571457/60978183-c3b01300-a2fe-11e9-80f2-36b6f4a72203.png)
![Screen Shot 2019-07-10 at 9 34 05 AM](https://user-images.githubusercontent.com/4571457/60978184-c3b01300-a2fe-11e9-8a5d-494f9f6b80eb.png)
![Screen Shot 2019-07-10 at 9 33 02 AM](https://user-images.githubusercontent.com/4571457/60978186-c3b01300-a2fe-11e9-8980-2fc822cf05a4.png)
![Screen Shot 2019-07-10 at 9 32 03 AM](https://user-images.githubusercontent.com/4571457/60978187-c3b01300-a2fe-11e9-9152-01646b58546c.png)

**Comment by ryangwilson** [comment]
Padding and colors mode to be more similar to current live version (right)
<img width="1920" alt="Screen Shot 2019-07-10 at 10 10 36 PM" src="https://user-images.githubusercontent.com/4571457/61019530-82544d80-a368-11e9-8cf6-5376dec4e4d9.png">
<img width="724" alt="Screen Shot 2019-07-10 at 11 17 26 PM" src="https://user-images.githubusercontent.com/4571457/61019643-eb3bc580-a368-11e9-8231-b8afe4834c0c.png">
<img width="1717" alt="Screen Shot 2019-07-10 at 11 18 17 PM" src="https://user-images.githubusercontent.com/4571457/61019676-060e3a00-a369-11e9-875d-437dd9cacae7.png">

**Comment by ryangwilson** [comment]
<img width="614" alt="Screen Shot 2019-07-10 at 11 19 39 PM" src="https://user-images.githubusercontent.com/4571457/61019731-3a81f600-a369-11e9-8155-eb992984c9fd.png">
