### ISSUE TITLE
CanJS6 - HTML Guide assets

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5243]
For the HTML Guide we have an embedded YouTube video and some images that will need to be updated.

https://canjs.com/doc/guides/html.html

- [ ] [Video](https://www.youtube.com/embed/3zMwoEuyX9g)
- [x] [Observable DOM Image](https://canjs.com/docs/can-guides/experiment/technology/observables-dom.png)
  - `can-component` -> `can-stache-element`
  - `can-define` -> `can-observable-object`, `can-observable-array` (on two lines)
- [x] [Can Component Image](https://canjs.com/docs/can-guides/experiment/technology/can-component.png)
  - `.view` -> `static view`
  - `.ViewModel` -> `static props`
  - `can-define` -> `can-observable-object`, `can-observable-array` (on two lines)
- [x] [Component Architecture Image](https://canjs.com/docs/can-guides/experiment/technology/component-architecture-overview.png)
  - `.view` -> `static view`
  - `.ViewModel` -> `static props`

**Comment by ryangwilson** [comment]
![observables-dom](https://user-images.githubusercontent.com/4571457/64174745-ea368a00-ce27-11e9-9a1f-af8a7f52fbff.png)
![can-component](https://user-images.githubusercontent.com/4571457/64174746-eacf2080-ce27-11e9-8a71-93768099a20e.png)
![component-architecture-overview](https://user-images.githubusercontent.com/4571457/64174747-eacf2080-ce27-11e9-844b-33ce799de327.png)

**Comment by ryangwilson** [comment]
Adding these as you might need them later
![component-architecture-overview-sm](https://user-images.githubusercontent.com/4571457/64176450-7a2a0300-ce2b-11e9-809a-9bd77c300eee.png)
![oveview](https://user-images.githubusercontent.com/4571457/64176451-7a2a0300-ce2b-11e9-9579-07f6948432f8.png)

**Comment by phillipskevin** [comment]
@ryangwilson, in https://user-images.githubusercontent.com/4571457/64176423-6ed6d780-ce2b-11e9-8bfe3-96e468ad8992.png and https://user-images.githubusercontent.com/4571457/64179790-b95b5280-ce31-11e9-8032-ec05790facb0.png

can we change
- `static props` to `properties` and
- `static view` to `view` 

Otherwise, these look good (https://user-images.githubusercontent.com/4571457/64179454-34703900-ce31-11e9-9a12-7002c5b50c17.png can keep `static props` and `static view`... it makes sense in this one).

**Comment by ryangwilson** [comment]
SVGs refined, optimized, tested in Safari, and zipped up
[svgs.zip](https://github.com/canjs/canjs/files/3570271/svgs.zip)
