### ISSUE TITLE
Inconsistent templated event handling for deep Map properties in can.Control

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#831]
Please review the simple example: http://jsfiddle.net/PJV2W/1/

Basically, as you can see, live data binding in views detects changes in deep property path at any level of property chain and handles object replacement gracefully. 

It does not happen in templated event handing for map.Control. Looks like event handlers are initialized for the whole chain only once, upon initialization time. And control did not monitor the changes in the property chain. I think it's an issue, which should be eliminated in the future CanJS releases.

**Comment by alexisabril** [comment]
@isadovskiy I agree this is a bit tricky from the developer's perspective. Think of it this way: templated event handlers are really just shorthand for binding to events.

For example:

```
'{game.team.player} change': function() {}

// is equivalent to

game.team.player.bind('set', function() {});
//The above line is pseudo code, only to stress a point
```

In the pseudo line, if player is replaced with a new object, we also lose the binding. This is actually what is happening in your example. If you add a call to [on()](http://canjs.com/docs/can.Control.prototype.on.html), you'll get the rebound player callback: http://jsfiddle.net/9yrm92f4/

In a view, this will work because we're actually setting up bindings on each section of your string: game, team and player. If any change, we'll re-evaluate the property/helper. For a control however, it's a more specific syntax. When is a property added, removed or set. Binding on each section in a control would be expensive.

I'm not closing this issue immediately as it's possible we could re-evaluate this approach in the future.

**Comment by justinbmeyer** [comment]
This is fixed in can-component.
